version: '3.8'

services:  
  sales-db:
    image: mysql:latest # use latest version of mysql
    container_name: sales-db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  
  sales-api:
    container_name: sales-api
    build: ./sales-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./sales-api:/app
      - /app/node_modules

volumes: # add persistent data even if container is removed.
  my-db:
